---
title: "SS Labo4"
author: "Ward"
date: "2017 M11 17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = TRUE, warning = FALSE}
library(leaflet)
#quakes = matrix( c(5.384984, 50.927781,5.348996, 50.9373317), nrow=2, ncol= 2, byrow = TRUE)
#dimnames(quakes) = list(c("row1", "row2"),c("long","lat"))

EAIcon <- makeIcon(
  iconUrl = "http://pxl-ea-ict.be/trinity/images/2.png",
  iconWidth = 80, iconHeight = 50,
  iconAnchorX = 11, iconAnchorY = 47)
  
MADIcon <- makeIcon(
  iconUrl = "https://www.pxl.be/Assets/website/pxl_algemeen/afbeeldingen/grotere_versie/1314_logo_pxl_mad.png",
  iconWidth = 40, iconHeight = 20,
  iconAnchorX = 0, iconAnchorY = 0)
BusinessIcon <- makeIcon(
  iconUrl = "https://www.pxl.be/Assets/website/pxl_algemeen/afbeeldingen/grotere_versie/1314_logo_pxl_business.png",
  iconWidth = 70, iconHeight = 20,
  iconAnchorX = 0, iconAnchorY = 0)
GeneeskundeIcon <- makeIcon(
  iconUrl = "https://www.pxl.be/Assets/website/pxl_algemeen/afbeeldingen/grotere_versie/1314_logo_pxl_healthcare.png",
  iconWidth = 70, iconHeight = 20,
  iconAnchorX = 0, iconAnchorY = 0)
EduIcon <- makeIcon(
  iconUrl = "https://www.pxl.be/Assets/website/pxl_algemeen/afbeeldingen/grotere_versie/1314_logo_pxl_education.png",
  iconWidth = 70, iconHeight = 20,
  iconAnchorX = 0, iconAnchorY = 0)
MusicIcon <- makeIcon(
  iconUrl = "https://www.pxl.be/Assets/website/pxl_algemeen/afbeeldingen/grotere_versie/1314_logo_pxl_music.png",
  iconWidth = 60, iconHeight = 20,
  iconAnchorX = 0, iconAnchorY = 0)




#EA_map <- leaflet() %>% 
 # leaflet(data = quakes[1:2,]) %>% addTiles() %>%
  #addMarkers(~long, ~lat, icon = greenLeafIcon)
EA_map <-  leaflet() %>% addTiles() %>%
  
  #setView(lng=5.369726, lat=50.929622, zoom  = 14 )%>%
  addMarkers(lng=5.384984, lat=50.927781,icon = EAIcon)%>%
  addMarkers(lng=5.352468, lat=50.939901,icon = MusicIcon)%>%
  addMarkers(lng=5.344791, lat=50.935136,icon = EduIcon)%>%
  addMarkers(lng=5.342426, lat=50.927944,icon = GeneeskundeIcon)%>%
  addMarkers(lng=5.348741, lat=50.938260,icon = BusinessIcon)%>%
  addMarkers(lng=5.350031, lat=50.937953,icon = MADIcon)
 
EA_map


```
